# Generated by Django 3.2 on 2021-04-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'verbose_name': '超华内容表', 'verbose_name_plural': '超华内容表'},
        ),
        migrations.AlterModelTable(
            name='bloginfo',
            table='blogInfo',
        ),
    ]
