# Generated by Django 3.2 on 2021-04-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210422_1259'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloginfo',
            table='blogs',
        ),
    ]
