# Generated by Django 3.2 on 2021-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bloginfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='analysis_sentiment',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
