# Generated by Django 3.2 on 2021-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210422_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='analysis_sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='analysis_sentiment',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
