# Generated by Django 3.2 on 2021-04-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210422_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='analysis_sentiment',
            new_name='sentiment',
        ),
        migrations.RenameField(
            model_name='bloginfo',
            old_name='analysis_sentiment_score',
            new_name='sentiment_score',
        ),
    ]
