# Generated by Django 3.2 on 2021-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210422_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=64)),
                ('creator_nickname', models.CharField(max_length=64)),
                ('creator_gender', models.CharField(max_length=16)),
                ('blog_counts', models.IntegerField(blank=True, null=True)),
                ('creator_sentiment', models.CharField(blank=True, max_length=16, null=True)),
                ('creator_sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': '超话用户',
                'verbose_name_plural': '超话用户',
                'db_table': 'supertopic_fans',
            },
        ),
    ]
