# Generated by Django 3.2 on 2021-04-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_creatorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='created_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
