# Generated by Django 3.2 on 2021-04-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210423_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
