# Generated by Django 3.2 on 2021-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210423_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorinfo',
            name='remark_text',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
