# Generated by Django 3.2 on 2021-04-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_creatorinfo_remark_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'verbose_name': '超话帖子', 'verbose_name_plural': '超话帖子'},
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
