# Generated by Django 3.2 on 2021-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210425_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='created_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
