# Generated by Django 3.2 on 2021-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_bloginfo_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_content',
            field=models.CharField(max_length=1024, verbose_name='微博文本'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='created_time',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微博发布时间'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='creator_id',
            field=models.CharField(max_length=64, verbose_name='用户微博ID'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='creator_nickname',
            field=models.CharField(max_length=64, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='sentiment',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='微博情感偏向'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='微博情感分值'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='blog_counts',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户超话发帖数'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_gender',
            field=models.CharField(max_length=16, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_id',
            field=models.CharField(max_length=64, verbose_name='用户微博ID'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_nickname',
            field=models.CharField(max_length=64, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_sentiment',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='用户情感偏向'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='用户情感分值'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='remark_text',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='备注'),
        ),
    ]
