# Generated by Django 3.2 on 2021-04-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210425_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginfo',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='bloginfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='creatorinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='creator',
            field=models.ForeignKey(default='超级管理员', on_delete=django.db.models.deletion.DO_NOTHING, related_name='微博发布者ID', to='myapp.creatorinfo'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_id',
            field=models.CharField(blank=True, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='creator_nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微博发布者昵称'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='用户微博ID'),
        ),
    ]
