# Generated by Django 3.2 on 2021-04-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210427_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginfo',
            name='creator',
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='creator_id',
            field=models.CharField(default='超级管理员', max_length=32, verbose_name='微博发布者ID'),
        ),
    ]
