# Generated by Django 3.2 on 2021-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210427_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='creator_id',
            field=models.CharField(default='超级管理员', max_length=64, verbose_name='微博发布者ID'),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator_gender',
            field=models.CharField(max_length=64, verbose_name='用户性别'),
        ),
    ]
